pipeline {
  agent any

  stages {
    stage('Terraform Apply') {
      steps {
        withCredentials([
          string(credentialsId: 'AWS_ACCESS_KEY_ID_CRED_ID', variable: 'AWS_ACCESS_KEY_ID'),
          string(credentialsId: 'AWS_SECRET_ACCESS_KEY_CRED_ID', variable: 'AWS_SECRET_ACCESS_KEY')
        ]) {
          dir('Automation/terraform') {
            sh '''
              export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
              export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
              terraform init
              terraform apply -auto-approve
            '''
          }
        }
      }
    }

    stage('Ansible Deploy') {
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: 'jenkins-lightsail-key', keyFileVariable: 'SSH_KEY')]) {
          dir('Automation/ansible') {
            sh 'ansible-playbook -i inventory.ini playbook.yml --private-key $SSH_KEY -u ubuntu'
          }
        }
      }
    }
  }
}